routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CompanyController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employee', EmployeeController::class);
Route::resource('company', CompanyController::class);


Route::get('/download-excell', [EmployeeController::class, 'export']);
Route::get('/download-pdf', [EmployeeController::class, 'DomPDF']);

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
     protected $table = 'company'; 

    protected $fillable = [
        'nama',
        'alamat',
    ];
}

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    protected $table = 'employee'; 

    protected $fillable = [
        'nama',
        'atasan_id',
        'company_id',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use Illuminate\Http\Request;


class CompanyController extends Controller
{
    public function index()
    {
        //fungsi eloquent menampilkan data menggunakan pagination
        $company = Company::latest()->paginate(5);
        return view('company.index', compact('company'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('company.create');
    }

    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            'nama' => 'required',
            'alamat' => 'required',
        ]);

        //fungsi eloquent untuk menambah data
        Company::create($request->all());

        //jika data berhasil ditambahkan, akan kembali ke halaman utama
        return redirect()->route('company.index')
            ->with('success', 'Company Berhasil Ditambahkan');
    }

    public function show($id)
    {
        //menampilkan detail data dengan menemukan/berdasarkan id employee
        $company = Company::find($id);
        return view('company.detail', compact('company'));
    }

    public function edit($id)
    {
        //menampilkan detail data dengan menemukan/berdasarkan id employee untuk diedit
        $company = Company::find($id);
        return view('company.edit', compact('company'));
    }

    public function update(Request $request, $id)
    {
        //melakukan validasi data
        $request->validate([
            'nama' => 'required',
            'alamat' => 'required',
        ]);

        //fungsi eloquent untuk mengupdate data inputan kita
        Company::find($id)->update($request->all());

        //jika data berhasil diupdate, akan kembali ke halaman utama
        return redirect()->route('company.index')
            ->with('success', 'Company Berhasil Diupdate');
    }

    public function destroy($id)
    {
        //fungsi eloquent untuk menghapus data
        Company::find($id)->delete();
        return redirect()->route('company.index')
            ->with('success', 'Company Berhasil Dihapus');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;
use App\Exports\EmployeesExport;
use Barryvdh\DomPDF\Facade as PDF;
use Maatwebsite\Excel\Facades\Excel;



class EmployeeController extends Controller
{
    public function index()
    {
        //fungsi eloquent menampilkan data menggunakan pagination
        $employee = Employee::latest()->paginate(5);
        return view('employee.index', compact('employee'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    public function create()
    {
        return view('employee.create');
    }

    public function store(Request $request)
    {
        //melakukan validasi data
        $request->validate([
            'nama' => 'required',
            'jabatan_id' => 'required',
            'company_id' => 'required',
        ]);

        //fungsi eloquent untuk menambah data
        Employee::create($request->all());

        //jika data berhasil ditambahkan, akan kembali ke halaman utama
        return redirect()->route('employee.index')
            ->with('success', 'Employee Berhasil Ditambahkan');
    }

    public function show($id)
    {
        //menampilkan detail data dengan menemukan/berdasarkan id employee
        $employee = Employee::find($id);
        return view('employee.detail', compact('employee'));
    }

    public function edit($id)
    {
        //menampilkan detail data dengan menemukan/berdasarkan id employee untuk diedit
        $employee = Employee::find($id);
        return view('employee.edit', compact('employee'));
    }

    public function update(Request $request, $id)
    {
        //melakukan validasi data
        $request->validate([
            'nama' => 'required',
            'jabatan_id' => 'required',
            'company_id' => 'required',
        ]);

        //fungsi eloquent untuk mengupdate data inputan kita
        Employee::find($id)->update($request->all());

        //jika data berhasil diupdate, akan kembali ke halaman utama
        return redirect()->route('employee.index')
            ->with('success', 'Employee Berhasil Diupdate');
    }

    public function destroy($id)
    {
        //fungsi eloquent untuk menghapus data
        Employee::find($id)->delete();
        return redirect()->route('employee.index')
            ->with('success', 'Employee Berhasil Dihapus');
    }

      public function export()
    {
        return Excel::download(new EmployeesExport, 'employee.xlsx');
    }

    public function DomPDF()
    {
        $employee = Employee::get();
        $pdf = PDF::loadView('print.index', ['employee' => $employee])->setOptions(['dpi' => 150, 'defaultFont' => 'sans-serif']);
        return $pdf->download('employee.pdf');
    }

}

resources/views/company/create.blade.php
@extends('layout')
  
@section('content')
   
<div class="container mt-5">
   
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Tambah Company
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('company.store') }}" id="myForm">
            @csrf
                <div class="form-group">
                    <label for="nama">Nama</label>                    
                    <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama" >                
                </div>
                <div class="form-group">
                    <label for="nama">Alamat</label>                    
                    <input type="text" name="alamat" class="form-control" id="alamat" aria-describedby="alamat" >                
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/company/edit.blade.php
@extends('layout')
  
@section('content')
   
<div class="container mt-5">
   
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Edit Company
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('company.update', $company->id) }}" id="myForm">
            @csrf
            @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>                    
                    <input type="text" name="nama" class="form-control" id="nama" value="{{ $company->nama }}" aria-describedby="nama" >                
                </div>
                <div class="form-group">
                    <label for="name">Alamat</label>                    
                    <input type="text" name="alamat" class="form-control" id="alamat" value="{{ $company->alamat }}" aria-describedby="alamat" >                
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/company/index.blade.php
@extends('layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mt-2">
                <h2>Laravel 8 CRUD - Manajemen Company</h2>
            </div>
            <div class="float-right my-2">
                <a class="btn btn-success" href="{{ route('company.create') }}"> Create New Company</a>
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Alamat</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($company as $item)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $item->nama }}</td>
            <td>{{ $item->alamat }}</td>
            <td>
                <form action="{{ route('company.destroy',$item->id) }}" method="POST">
   
                    <!-- <a class="btn btn-info" href="{{ route('employee.show',$item->id) }}">Show</a> -->
    
                    <a class="btn btn-primary" href="{{ route('company.edit',$item->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    <div class="text-center">
        {!! $company->links() !!}
    </div>
      
@endsection

resources/views/employee/create.blade.php
@extends('layout')
  
@section('content')
   
<div class="container mt-5">
   
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Tambah Employee
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('employee.store') }}" id="myForm">
            @csrf
                <div class="form-group">
                    <label for="nama">Nama</label>                    
                    <input type="text" name="nama" class="form-control" id="nama" aria-describedby="nama" >                
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Pilih Atasan</label>
                        <select name="jabatan_id" class="form-control">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>          
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Pilih Company</label>
                        <select name="company_id" class="form-control">
                        <option value="1">1</option>
                        <option value="2">2</option>
                    </select>                  
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
    </div>
@endsection

resources/views/employee/edit.blade.php
@extends('layout')
  
@section('content')
   
<div class="container mt-5">
   
    <div class="row justify-content-center align-items-center">
        <div class="card" style="width: 24rem;">
            <div class="card-header">
            Edit User
            </div>
            <div class="card-body">
                @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('employee.update', $employee->id) }}" id="myForm">
            @csrf
            @method('PUT')
                <div class="form-group">
                    <label for="name">Name</label>                    
                    <input type="text" name="nama" class="form-control" id="nama" value="{{ $employee->nama }}" aria-describedby="nama" >                
                </div>
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Pilih Atasan</label>
                        <select name="atasan_id" class="form-control">
                        <option value="1" {{ ($employee->atasan_id == 1) ? 'selected' : '' }}> 1 </option>
                        <option value="2" {{ ($employee->atasan_id == 2) ? 'selected' : '' }}> 2 </option>
                        <option value="3" {{ ($employee->atasan_id == 3) ? 'selected' : '' }}> 3 </option>
                        <option value="4" {{ ($employee->atasan_id == 4) ? 'selected' : '' }}> 4 </option>
                        <option value="5" {{ ($employee->atasan_id == 5) ? 'selected' : '' }}> 5 </option>
                    </select>                     
                </div>
                <div class="form-group">
                     <label for="exampleFormControlSelect1">Pilih Company</label>
                        <select name="company_id" class="form-control">
                        <option value="1" {{ ($employee->company_id == 1) ? 'selected' : '' }}> 1 </option>
                        <option value="2" {{ ($employee->company_id == 2) ? 'selected' : '' }}> 2 </option>
                    </select>                    
                </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employee/index.blade.php
@extends('layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left mt-2">
                <h2>Laravel 8 CRUD - Manajemen Employee</h2>
            </div>
            <div class="float-right my-2">
                <a class="btn btn-success" href="{{ route('employee.create') }}"> Create New Employee</a>
            </div>
                  <div class="d-flex justify-content-left mb-5">
                    <a href="/download-excell" class="btn btn-sm btn-success rounded-pill mx-2">Download Excell</a>
                    <a href="/download-pdf" class="btn btn-sm btn-success rounded-pill mx-2">Download PDF</a>
                </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Nama</th>
            <th>Atasan</th>
            <th>Company</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($employee as $item)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $item->nama }}</td>
            <td>{{ $item->atasan_id }}</td>
            <td>{{ $item->company_id }}</td>
            <td>
                <form action="{{ route('employee.destroy',$item->id) }}" method="POST">
   
                    <!-- <a class="btn btn-info" href="{{ route('employee.show',$item->id) }}">Show</a> -->
    
                    <a class="btn btn-primary" href="{{ route('employee.edit',$item->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
    <div class="text-center">
        {!! $employee->links() !!}
    </div>
@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
    <head>
        <title>Sistem Informasi Manajemen Stuktur Organisasi</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            @yield('content')
        </div>
    </body>
</html>

resources/views/print/index.blade.php
<style>
table, th, td {
  border: 1px solid black;
}
</style>
<table class="table table-bordered">
    <thead>
      <tr >
        <th scope="col">id</th>
        <th scope="col">Nama</th>
        <th scope="col">Posisi</th>
        <th scope="col">Perusahaan</th>
      </tr>
    </thead>
    <tbody>
        @foreach ($employee as $employee)
        <tr>
        <th scope="row">{{ $employee->id }}</th>
        <td>{{ $employee->nama }}</td>
        <td>{{ $employee->atasan_id }}</td>
        <td>{{ $employee->company_id }}</td>
        </tr>
        @endforeach
    </tbody>
  </table>